<a href="https://colab.research.google.com/github/shturman637/ProgIng/blob/main/Untitled18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Импортируем библиотеки

In [8]:
import pandas as pd # Библиотека Pandas для работы с табличными данными
import numpy as np # библиотека Numpy для операций линейной алгебры и прочего
import matplotlib.pyplot as plt # библиотека Matplotlib для визуализации
import seaborn as sns # библиотека seaborn для визуализации
import numpy as np # библиотека Numpy для операций линейной алгебры и прочего

# предварительная обработка числовых признаков
from sklearn.preprocessing import MinMaxScaler# Импортируем нормализацию от scikit-learn
from sklearn.preprocessing import StandardScaler # Импортируем стандартизацию от scikit-learn
from sklearn.preprocessing import PowerTransformer  # Степенное преобразование от scikit-learn
# предварительная обработка категориальных признаков
from sklearn.preprocessing import OneHotEncoder# Импортируем One-Hot Encoding от scikit-learn
from sklearn.preprocessing import OrdinalEncoder# Импортируем Порядковое кодированиеот scikit-learn

from sklearn.pipeline import Pipeline # Pipeline.Не добавить, не убавить

from sklearn.compose import ColumnTransformer # т.н. преобразователь колонок

from sklearn.base import BaseEstimator, TransformerMixin # для создания собственных преобразователей / трансформеров данных

In [9]:
import warnings
warnings.filterwarnings('ignore')

# Набор данных
Загружаем набор данных [Healthcare Insurance](https://www.kaggle.com/datasets/willianoliveiragibin/healthcare-insurance/data) с сайта Kaggle.

insurance.csv

Этот набор данных содержит информацию о взаимосвязи между личными характеристиками (возраст, пол, ИМТ, размер семьи, привычки курить), географическими факторами и их влиянием на расходы по медицинскому страхованию. Его можно использовать для изучения того, как эти особенности влияют на стоимость страхования, и разработки прогностических моделей для оценки расходов на здравоохранение.

# Загружаем данные в Pandas

In [10]:
df = pd.read_csv('insurance.csv', delimiter = ',')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

# Информация о DataFrame

In [11]:
df.info() # информация о данных в DataFrame:
#сколько строк,
#какие данные в столбцах,
#сколько пропущенных значений (Nan-values)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

 Набор данных содержит 1338 строк, 7 признаков, пропущенных значений нет.

# Поиск и удаление дубликатов

In [13]:
df.duplicated().sum() # узнаем сколько всего  дубликатов в нашем наборе данных

1

In [14]:
DF = df.drop_duplicates() # Складываем в новый DataFrame результат удаления дубликатов

DF = DF.reset_index(drop=True) # обновим индексы в DataFrame DF.
# если бы мы прописали drop = False, то была бы еще одна колонка - старые индексы

DF

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1332   50    male  30.970         3     no  northwest  10600.54830
1333   18  female  31.920         0     no  northeast   2205.98080
1334   18  female  36.850         0     no  southeast   1629.83350
1335   21  female  25.800         0     no  southwest   2007.94500
1336   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [15]:
DF.duplicated().sum() # проверили что дубликатов нет

0

In [16]:
DF.info() # посмотрим теперь информацию о наборе данных

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   object
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   object
 5   region    1337 non-null   object
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB

Теперь набор данных содержит 1337 строк, 7 признаков, пропущенных значений нет.